# Generated by Django 4.0.2 on 2022-03-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='product_id')),
                ('name_of_prod', models.CharField(max_length=50, verbose_name='name_of_product')),
                ('price', models.DecimalField(decimal_places=4, max_digits=9, verbose_name='price')),
                ('currency', models.CharField(default='euros', max_length=10, verbose_name='currency')),
            ],
        ),
    ]
