# Generated by Django 4.0.2 on 2022-03-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='product_id')),
                ('name_of_prod', models.CharField(max_length=50, unique=True, verbose_name='name_of_product')),
                ('slug', models.SlugField(help_text='Unique Value for product page URL, created from name.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('currency', models.CharField(default='euros', max_length=10, verbose_name='currency')),
                ('image', models.ImageField(upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(null=True)),
                ('meta_keywords', models.CharField(help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, null=True)),
                ('meta_description', models.CharField(help_text='Content for description meta tag', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
