# Generated by Django 4.0.2 on 2022-03-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_of_prod',
            field=models.CharField(max_length=50, verbose_name='name_of_product'),
        ),
    ]
