version: "3.7"

services:
  # Proxies requests to internal services
#  django_admin_db:
#    image: postgres:13-alpine
#    container_name: django_admin_db
#    restart: unless-stopped
#    env_file:
#      - ./.env
#    ports:
#      - 5432:5432
#    volumes:
#      - databases:/var/lib/postgresql/data
#    networks:
#      - django_admin

  django_admin:
    image: django_admin
    build:
      context: .
    container_name: django_admin
    volumes:
      - static_data:/vol/web
      - static_media:/vol/media
    env_file:
      - ./.env
    ports:
    - 9194:9194
#    links:
#      - django_admin_db:django_admin_db
#    depends_on:
#      - django_admin_db
    networks:
      - django_admin
    restart: unless-stopped

  server:
    image: server
    container_name: server
    build:
      context: ./dev
    volumes:
      - static_data:/vol/static
      - static_media:/vol/media
    restart: unless-stopped
    depends_on:
      - django_admin

volumes:
#  databases:
  static_media:
  static_data:

networks:
  django_admin:
    driver: bridge