# Generated by Django 4.0.2 on 2022-03-25 22:03

from django.db import migrations, models
import payment.models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default=1, max_length=100, verbose_name='order_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.CharField(default=1, max_length=30, verbose_name='total_amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default=payment.models.increment_payment_id, max_length=20, verbose_name='payment_id'),
        ),
    ]
