# Generated by Django 4.0.2 on 2022-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='order_id'),
        ),
    ]
