# Generated by Django 4.0.2 on 2022-03-19 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='corporate_client_id')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='company_name')),
                ('slug', models.SlugField(help_text='Unique Value for product page URL, created from name.', max_length=255)),
                ('company_type', models.CharField(choices=[('miss', 'Miss'), ('mr', 'Mr.'), ('mrs', 'Mrs.')], max_length=50, verbose_name='company_type')),
                ('nature_of_business', models.CharField(max_length=255, null=True, verbose_name='nature_of_business')),
                ('industry_sector', models.CharField(max_length=100, verbose_name='industry_sector')),
                ('vat_reg_no', models.CharField(max_length=255, verbose_name='vat_reg_no')),
                ('main_contact_number', models.CharField(max_length=20, unique=True, verbose_name='company_phone')),
                ('main_contact_email', models.EmailField(max_length=254, unique=True, verbose_name='company_email')),
                ('no_of_employees', models.IntegerField(verbose_name='no_of_employees')),
                ('no_of_years', models.IntegerField(verbose_name='no_years_of_trade')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal_code')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('pur_system', models.BooleanField(verbose_name='pur_order_sy')),
                ('bill_name', models.CharField(max_length=255, null=True, verbose_name='billing_name')),
                ('bill_phone', models.IntegerField(null=True, verbose_name='billing_phone')),
                ('bill_email', models.EmailField(max_length=254, null=True, verbose_name='company_email')),
                ('auth_prsnl_first_name', models.CharField(max_length=100, null=True, verbose_name='auth_personel_frst_name')),
                ('auth_prsnl_last_name', models.CharField(max_length=100, null=True, verbose_name='auth_personel_last_name')),
                ('auth_prsnl_title', models.CharField(choices=[('Miss', 'Miss'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.')], max_length=20, null=True, verbose_name='auth_personel_title')),
                ('preferred_mode', models.CharField(choices=[('agender', 'Agender'), ('androgyne', 'Androgyne'), ('gender_fluid', 'Gender Fluid'), ('male', 'Male'), ('non_binary', 'Non Binary'), ('transgender', 'Transgender'), ('female', 'Female')], max_length=100, verbose_name='preferred_mode')),
                ('sub_newsletter', models.BooleanField(default=True, verbose_name='sub_newsletter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corporate_client',
            },
        ),
        migrations.CreateModel(
            name='InternetClient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='client_id')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('title', models.CharField(choices=[('Miss', 'Miss'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.')], max_length=20, null=True, verbose_name='title')),
                ('phone', models.IntegerField(unique=True, verbose_name='phone_number')),
                ('dob', models.DateField(verbose_name='date_of_birth')),
                ('gender', models.CharField(choices=[('agender', 'Agender'), ('androgyne', 'Androgyne'), ('gender_fluid', 'Gender Fluid'), ('male', 'Male'), ('non_binary', 'Non Binary'), ('transgender', 'Transgender'), ('female', 'Female')], max_length=50, verbose_name='gender')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal_code')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Unique Value for product page URL, created from name.', max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('crprt_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_mgt.corporateclient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internet_client',
            },
        ),
    ]
