# Generated by Django 4.0.2 on 2022-03-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetclient',
            name='verified',
        ),
        migrations.AddField(
            model_name='internetclient',
            name='status',
            field=models.CharField(choices=[(0, 'visitor'), (1, 'unverified customer'), (2, 'verified customer')], default=0, max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='internetclient',
            name='phone',
            field=models.IntegerField(verbose_name='phone_number'),
        ),
    ]
