# Generated by Django 4.0.2 on 2022-03-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateclient',
            name='auth_prsnl_first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='auth_personel_frst_name'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='auth_prsnl_last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='auth_personel_last_name'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='bill_email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='company_email'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='bill_name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='billing_name'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='bill_phone',
            field=models.IntegerField(null=True, unique=True, verbose_name='billing_phone'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='company_type',
            field=models.CharField(choices=[('miss', 'Miss'), ('mr', 'Mr.'), ('mrs', 'Mrs.')], max_length=50, verbose_name='company_type'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='preferred_mode',
            field=models.CharField(choices=[('agender', 'Agender'), ('androgyne', 'Androgyne'), ('gender_fluid', 'Gender Fluid'), ('male', 'Male'), ('non_binary', 'Non Binary'), ('transgender', 'Transgender'), ('female', 'Female')], max_length=100, verbose_name='preferred_mode'),
        ),
    ]
