# Generated by Django 4.0.2 on 2022-03-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0002_alter_corporateclient_auth_prsnl_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateclient',
            name='bill_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='company_email'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='bill_name',
            field=models.CharField(max_length=255, null=True, verbose_name='billing_name'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='bill_phone',
            field=models.IntegerField(null=True, verbose_name='billing_phone'),
        ),
    ]
