# Generated by Django 4.0.2 on 2022-03-12 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0003_alter_corporateclient_bill_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetclient',
            name='crprt_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_mgt.corporateclient'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='auth_prsnl_title',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.')], max_length=20, null=True, verbose_name='auth_personel_title'),
        ),
        migrations.AlterField(
            model_name='internetclient',
            name='title',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.')], max_length=20, null=True, verbose_name='title'),
        ),
    ]
