# Generated by Django 4.0.2 on 2022-03-19 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client_mgt', '0003_alter_internetclient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetclient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
