# Generated by Django 4.0.2 on 2022-03-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0004_internetclient_crprt_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetclient',
            name='slug',
            field=models.SlugField(default='happy', help_text='Unique Value for product page URL, created from name.', max_length=255),
            preserve_default=False,
        ),
    ]
