# Generated by Django 4.0.2 on 2022-04-04 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0005_remove_corporateclient_auth_prsnl_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internetclient',
            old_name='crprt_client',
            new_name='cor_comp',
        ),
    ]
