# Generated by Django 4.0.2 on 2022-03-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0005_internetclient_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetclient',
            name='email',
            field=models.EmailField(default='h', max_length=254, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internetclient',
            name='first_name',
            field=models.CharField(default=8, max_length=100, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internetclient',
            name='last_name',
            field=models.CharField(default='8', max_length=100, verbose_name='last_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internetclient',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
