# Generated by Django 4.0.2 on 2022-05-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0006_rename_crprt_client_internetclient_cor_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internetclient',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='phone_number'),
        ),
    ]
