# Generated by Django 4.0.2 on 2022-05-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0007_alter_internetclient_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateclient',
            name='preferred_mode',
        ),
        migrations.AddField(
            model_name='corporateclient',
            name='main_contact_name',
            field=models.CharField(default='l', max_length=100, verbose_name='main_contact_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='bill_phone',
            field=models.CharField(max_length=15, null=True, verbose_name='billing_phone'),
        ),
        migrations.AlterField(
            model_name='corporateclient',
            name='company_type',
            field=models.CharField(choices=[('Sole Trader', 'Sole Trader'), ('Limited Company', 'Limited Company'), ('Partnership', 'Partnership'), ('LLP', 'LLP')], max_length=50, verbose_name='company_type'),
        ),
    ]
