# Generated by Django 4.0.2 on 2022-03-26 21:57

from django.db import migrations, models
import e_mail.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('email_id', models.CharField(default=e_mail.models.increment_email_id, max_length=20, verbose_name='email_id')),
                ('subject', models.CharField(max_length=100, verbose_name='subject')),
                ('body_txt', tinymce.models.HTMLField()),
            ],
        ),
    ]
