# Generated by Django 4.0.2 on 2022-03-28 07:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail', '0002_e_mail_body_html_e_mail_title_alter_e_mail_body_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_mail',
            name='body_html',
            field=tinymce.models.HTMLField(default='<h1>hi</hi>'),
        ),
        migrations.AlterField(
            model_name='e_mail',
            name='body_txt',
            field=models.TextField(default='ho', verbose_name='body_txt'),
        ),
    ]
