# Generated by Django 4.0.2 on 2022-03-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail', '0004_alter_e_mail_body_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_mail',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='description'),
            preserve_default=False,
        ),
    ]
