# Generated by Django 4.0.2 on 2022-03-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_mail', '0005_e_mail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_mail',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='e_mail',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='title'),
        ),
    ]
