# Generated by Django 4.0.2 on 2022-03-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_mgt', '0005_internetclient_slug'),
        ('clinic_mgt', '0002_alter_doctor_slug_delete_appointmentdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='appointment_id')),
                ('time', models.DateTimeField(verbose_name='appointment_time')),
                ('notes', models.TextField(verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_mgt.internetclient')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.doctor')),
            ],
        ),
    ]
