# Generated by Django 4.0.2 on 2022-03-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0001_initial'),
        ('client_mgt', '0001_initial'),
        ('prod_mgt', '0003_alter_product_name_of_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='appointment_id')),
                ('notes', models.TextField(null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(0, 'not paid'), (1, 'paid')], max_length=20, verbose_name='status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_mgt.internetclient')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedules.scheduledates')),
            ],
        ),
        migrations.CreateModel(
            name='ICOrders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='order_id')),
                ('order_number', models.IntegerField(null=True, verbose_name='order_number')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('total_price', models.IntegerField(verbose_name='total_price')),
                ('payment_status', models.CharField(choices=[('failed', 'failed'), ('refund', 'refund'), ('success', 'success'), ('pending', 'pending')], max_length=30, verbose_name='payment_status')),
                ('order_medium', models.CharField(choices=[('portal', 'portal'), ('website', 'website')], max_length=30, verbose_name='order_medium')),
                ('payment_medium', models.CharField(choices=[('stripe', 'stripe'), ('transfer', 'transfer')], max_length=30, verbose_name='payment_medium')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='fulfilled')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_mgt.internetclient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_mgt.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='cart_id')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_mgt.internetclient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_mgt.product')),
            ],
        ),
    ]
