# Generated by Django 4.0.2 on 2022-03-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='cart_id'),
        ),
    ]
