# Generated by Django 4.0.2 on 2022-03-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='day_of_week',
            field=models.CharField(max_length=10, null=True, verbose_name='day_of_week'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='e_time',
            field=models.TimeField(null=True, verbose_name='actual_end_time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='end_time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='s_time',
            field=models.TimeField(null=True, verbose_name='actual_star_time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='start_time'),
        ),
    ]
