# Generated by Django 4.0.2 on 2022-03-23 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='time_slot',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='schedules.timeslots'),
            preserve_default=False,
        ),
    ]
