# Generated by Django 4.0.2 on 2022-03-25 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '__first__'),
        ('booking', '0002_appointment_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICInvoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='invoice_number')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued_at')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.icorders')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
        ),
    ]
