# Generated by Django 4.0.2 on 2022-03-18 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0006_internetclient_email_internetclient_first_name_and_more'),
        ('booking', '0003_alter_appointment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='e_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='s_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(null=True, verbose_name='actual_end_time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(null=True, verbose_name='actual_start_time'),
        ),
        migrations.CreateModel(
            name='ICOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='order_id')),
                ('order_number', models.IntegerField(verbose_name='order_number')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('total_price', models.IntegerField(verbose_name='total_price')),
                ('payment_status', models.CharField(choices=[('failed', 'failed'), ('refund', 'refund'), ('success', 'success'), ('pending', 'pending')], max_length=30, verbose_name='payment_status')),
                ('order_medium', models.CharField(choices=[('portal', 'portal'), ('website', 'website')], max_length=30, verbose_name='order_medium')),
                ('payment_medium', models.CharField(choices=[('stripe', 'stripe'), ('transfer', 'transfer')], max_length=30, verbose_name='payment_medium')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='fulfilled')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_mgt.internetclient')),
            ],
        ),
    ]
