# Generated by Django 4.0.2 on 2022-03-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_icinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(default=1, max_length=20, verbose_name='appointment_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icorders',
            name='order_number',
            field=models.CharField(default=1, max_length=20, verbose_name='order_number'),
            preserve_default=False,
        ),
    ]
