# Generated by Django 4.0.2 on 2022-03-18 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod_mgt', '0003_alter_product_name_of_prod'),
        ('booking', '0004_remove_appointment_e_time_remove_appointment_s_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icorders',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prod_mgt.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icorders',
            name='order_number',
            field=models.IntegerField(null=True, verbose_name='order_number'),
        ),
    ]
