# Generated by Django 4.0.2 on 2022-03-25 22:20

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment_appointment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.CharField(default=booking.models.increment_app_id, max_length=20, verbose_name='appointment_id'),
        ),
        migrations.AlterField(
            model_name='icinvoice',
            name='invoice_number',
            field=models.CharField(default=booking.models.increment_invoice_number, max_length=20, verbose_name='invoice_number'),
        ),
        migrations.AlterField(
            model_name='icorders',
            name='order_number',
            field=models.CharField(default=booking.models.increment_ico_id, max_length=20, verbose_name='order_number'),
        ),
    ]
