# Generated by Django 4.0.2 on 2022-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_icorders_product_alter_icorders_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icorders',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='order_id'),
        ),
    ]
