# Generated by Django 4.0.2 on 2022-04-07 05:50

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_mgt', '0006_rename_crprt_client_internetclient_cor_comp'),
        ('payment', '0003_alter_payment_id'),
        ('schedules', '0005_alter_scheduledates_id_alter_timeslots_id'),
        ('prod_mgt', '0003_alter_product_name_of_prod'),
        ('booking', '0006_alter_icorders_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAppointment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='appointment_id')),
                ('appointment_id', models.CharField(default=booking.models.increment_app_id, max_length=20, verbose_name='appointment_id')),
                ('appointment_no', models.CharField(max_length=20, verbose_name='appointment_no')),
                ('notes', models.TextField(null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(0, 'not paid'), (1, 'paid')], max_length=20, verbose_name='status')),
                ('c_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_mgt.corporateclient')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_mgt.internetclient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod_mgt.product')),
                ('time_slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedules.timeslots')),
            ],
        ),
        migrations.CreateModel(
            name='CCOrders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='order_id')),
                ('order_number', models.CharField(default=booking.models.increment_ico_id, max_length=20, verbose_name='order_number')),
                ('appointment', models.CharField(max_length=20, verbose_name='appointment_number')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('total_price', models.IntegerField(verbose_name='total_price')),
                ('payment_status', models.CharField(choices=[('failed', 'failed'), ('refund', 'refund'), ('success', 'success'), ('pending', 'pending')], max_length=30, verbose_name='payment_status')),
                ('order_medium', models.CharField(choices=[('portal', 'portal'), ('website', 'website')], max_length=30, verbose_name='order_medium')),
                ('payment_medium', models.CharField(choices=[('stripe', 'stripe'), ('transfer', 'transfer')], max_length=30, verbose_name='payment_medium')),
                ('fulfilled', models.BooleanField(default=False, verbose_name='fulfilled')),
                ('c_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_mgt.corporateclient')),
            ],
        ),
        migrations.CreateModel(
            name='CCInvoice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('invoice_number', models.CharField(default=booking.models.increment_invoice_number, max_length=20, verbose_name='invoice_number')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued_at')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.ccorders')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.payment')),
            ],
        ),
        migrations.CreateModel(
            name='CCart',
            fields=[
                ('cart_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='cart_id')),
                ('appointment', models.CharField(max_length=20, verbose_name='appointment_no')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_mgt.corporateclient')),
            ],
        ),
    ]
