# Generated by Django 4.0.2 on 2022-04-14 09:39

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_corporateappointment_ccorders_ccinvoice_ccart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateappointment',
            name='appointment_no',
            field=models.CharField(default=booking.models.increment_app_no, max_length=20, verbose_name='appointment_no'),
        ),
    ]
