# Generated by Django 4.0.2 on 2022-05-07 13:53

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_ccorders_d_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccinvoice',
            name='invoice_number',
            field=models.CharField(default=booking.models.increment_cinvoice_number, max_length=20, verbose_name='invoice_number'),
        ),
        migrations.AlterField(
            model_name='ccinvoice',
            name='order',
            field=models.CharField(max_length=50, verbose_name='order_number'),
        ),
        migrations.AlterField(
            model_name='ccorders',
            name='order_number',
            field=models.CharField(max_length=20, verbose_name='order_number'),
        ),
    ]
