# Generated by Django 4.0.2 on 2022-05-09 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_ccinvoice_invoice_number_alter_ccinvoice_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icorders',
            name='cart',
            field=models.OneToOneField(default='sssssssssss', on_delete=django.db.models.deletion.CASCADE, to='booking.cart'),
            preserve_default=False,
        ),
    ]
