# Generated by Django 4.0.2 on 2022-05-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_appointment_time_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icorders',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.cart'),
        ),
    ]
