# Generated by Django 4.0.2 on 2022-05-22 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('booking', '0016_alter_icorders_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='icorders',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.coupon'),
        ),
    ]
