# Generated by Django 4.0.2 on 2022-05-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_cart_coupon_ccorders_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=-9999, max_digits=9, verbose_name='price'),
        ),
    ]
