# Generated by Django 4.0.2 on 2022-05-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_cart_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_val',
            field=models.IntegerField(default=0, verbose_name='no_of_redeem'),
        ),
    ]
