# Generated by Django 4.0.2 on 2022-05-23 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('booking', '0020_cart_coupon_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccart',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.coupon'),
        ),
        migrations.AddField(
            model_name='ccart',
            name='coupon_val',
            field=models.IntegerField(default=0, verbose_name='no_of_redeem'),
        ),
        migrations.AddField(
            model_name='ccart',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=-9999, max_digits=9, verbose_name='price'),
        ),
    ]
