# Generated by Django 4.0.2 on 2022-02-23 17:31

import clinic_mgt.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_contact_street_phone_status_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.IntegerField(default=clinic_mgt.models.clinic_id_increment, primary_key=True, serialize=False, unique=True, verbose_name='clinic_id')),
                ('name', models.CharField(max_length=100, verbose_name='clinic_name')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('available_to_work', models.BooleanField(default=False, verbose_name='available_to_work')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('first_name', models.CharField(max_length=20, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=20, verbose_name='last_name')),
                ('id', models.IntegerField(default=clinic_mgt.models.doctor_id_increment, primary_key=True, serialize=False, unique=True, verbose_name='doctor_id')),
                ('verified', models.BooleanField(default=False, verbose_name='verified')),
                ('available_to_work', models.BooleanField(default=False, verbose_name='available_to_work')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicLocation',
            fields=[
                ('id', models.IntegerField(default=clinic_mgt.models.cliniclocation_id_increment, primary_key=True, serialize=False, unique=True, verbose_name='clinic_location_id')),
                ('postal_code', models.CharField(max_length=10, verbose_name='postal_code')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic')),
            ],
        ),
    ]
