# Generated by Django 4.0.2 on 2022-03-08 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='clinic_id')),
                ('name', models.CharField(max_length=100, verbose_name='clinic_name')),
                ('verified', models.BooleanField(default=True, verbose_name='verified')),
                ('available_to_work', models.BooleanField(default=True, verbose_name='available_to_work')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_verify_doctors', 'Can verify Doctors')],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='doctor_id')),
                ('verified', models.BooleanField(default=True, verbose_name='verified')),
                ('available_to_work', models.BooleanField(default=True, verbose_name='available_to_work')),
                ('slug', models.SlugField(help_text='Unique Value for product page URL, created from name.')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicLocation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='clinic_location_id')),
                ('postal_code', models.CharField(max_length=10, verbose_name='postal_code')),
                ('address', models.CharField(max_length=100, verbose_name='postal_code')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='appointment_date_id')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('end_time', models.DateTimeField(verbose_name='end_time')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.doctor')),
            ],
        ),
    ]
