# Generated by Django 4.0.2 on 2022-03-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='clinic_id')),
                ('name', models.CharField(max_length=100, verbose_name='clinic_name')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='email')),
                ('postal_code', models.CharField(max_length=10, verbose_name='postal_code')),
                ('address', models.CharField(max_length=100, verbose_name='postal_code')),
                ('long', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='doctor_id')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('verified', models.BooleanField(default=True, verbose_name='verified')),
                ('available_to_work', models.BooleanField(default=True, verbose_name='available_to_work')),
                ('slug', models.SlugField(help_text='Unique Value for product page URL, created from name.', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
