# Generated by Django 4.0.2 on 2022-03-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(help_text='Unique Value for product page URL, created from name.', max_length=255),
        ),
        migrations.DeleteModel(
            name='AppointmentDates',
        ),
    ]
