# Generated by Django 4.0.2 on 2022-02-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='clinic_id'),
        ),
        migrations.AlterField(
            model_name='cliniclocation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='clinic_location_id'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='doctor_id'),
        ),
    ]
