# Generated by Django 4.0.2 on 2022-02-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0002_alter_clinic_id_alter_cliniclocation_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={'permissions': [('can_verify_doctors', 'Can verify Doctors')]},
        ),
    ]
