# Generated by Django 4.0.2 on 2022-04-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0002_clinic_avail_to_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='slug',
            field=models.SlugField(default='l', help_text='Unique Value for product page URL, created from name.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='clinic_name'),
        ),
    ]
