# Generated by Django 4.0.2 on 2022-03-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0002_alter_doctor_slug_delete_appointmentdates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic',
            options={},
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='available_to_work',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='clinic',
        ),
        migrations.AddField(
            model_name='clinic',
            name='address',
            field=models.CharField(default='i', max_length=100, verbose_name='postal_code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.CharField(default=9, max_length=100, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clinic',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='postal_code',
            field=models.CharField(default=7, max_length=10, verbose_name='postal_code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='first_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='last_name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClinicLocation',
        ),
    ]
