# Generated by Django 4.0.2 on 2022-02-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0003_alter_clinic_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='contact',
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='locality',
            field=models.CharField(default='null', max_length=30, verbose_name='locality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='number_street',
            field=models.CharField(default='null', max_length=30, verbose_name='num_street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='post_town',
            field=models.CharField(default='null', max_length=30, verbose_name='post_town'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='available_to_work',
            field=models.BooleanField(default=True, verbose_name='available_to_work'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='verified',
            field=models.BooleanField(default=True, verbose_name='verified'),
        ),
    ]
