# Generated by Django 4.0.2 on 2022-04-26 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0003_clinic_slug_alter_clinic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='email',
        ),
    ]
