# Generated by Django 4.0.2 on 2022-02-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0004_remove_clinic_contact_remove_doctor_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='available_to_work',
            field=models.BooleanField(default=True, verbose_name='available_to_work'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='verified',
            field=models.BooleanField(default=True, verbose_name='verified'),
        ),
    ]
