# Generated by Django 4.0.2 on 2022-03-03 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0005_remove_doctor_first_name_remove_doctor_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='appointment_date_id')),
                ('start_time', models.DateTimeField(verbose_name='start_time')),
                ('end_time', models.DateTimeField(verbose_name='end_time')),
                ('duration', models.IntegerField(verbose_name='duration')),
                ('clinic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.doctor')),
            ],
        ),
    ]
