# Generated by Django 4.0.2 on 2022-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0006_appointmentdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclocation',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=5, max_digits=9, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliniclocation',
            name='long',
            field=models.DecimalField(decimal_places=6, default=2, max_digits=9, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
