# Generated by Django 4.0.2 on 2022-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0007_cliniclocation_lat_cliniclocation_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclocation',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='cliniclocation',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
