# Generated by Django 4.0.2 on 2022-03-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0009_alter_cliniclocation_postal_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliniclocation',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='cliniclocation',
            name='number_street',
        ),
        migrations.RemoveField(
            model_name='cliniclocation',
            name='post_town',
        ),
    ]
