# Generated by Django 4.0.2 on 2022-03-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0010_remove_cliniclocation_locality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniclocation',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='postal_code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliniclocation',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='postal_code'),
        ),
    ]
