# Generated by Django 4.0.2 on 2022-03-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0011_cliniclocation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdates',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
