# Generated by Django 4.0.2 on 2022-03-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0013_alter_appointmentdates_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdates',
            name='duration',
        ),
    ]
