# Generated by Django 4.0.2 on 2022-03-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0014_remove_appointmentdates_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdates',
            name='slug',
        ),
    ]
