# Generated by Django 4.0.2 on 2022-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.CharField(default='Lagos, Nigeria', max_length=50, verbose_name='street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phone',
            name='status_id',
            field=models.IntegerField(default=12345, verbose_name='status_id'),
            preserve_default=False,
        ),
    ]
