# Generated by Django 4.0.2 on 2022-03-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='sarahu2noke@gmail.com', max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
