# Generated by Django 4.0.2 on 2022-02-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_contact_id_alter_phone_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='status_id',
            field=models.IntegerField(null=True, verbose_name='status_id'),
        ),
    ]
