# Generated by Django 4.0.2 on 2022-02-26 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0004_remove_clinic_contact_remove_doctor_contact_and_more'),
        ('authentication', '0005_alter_phone_status_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
