# Generated by Django 4.0.2 on 2022-03-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='time_slot_id')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('start_time', models.TimeField(verbose_name='actual_star_time')),
                ('end_time', models.TimeField(verbose_name='actual_end_time')),
                ('status', models.CharField(choices=[(0, 'not booked'), (1, 'temporarily booked'), ('2', 'paid for')], max_length=10, verbose_name='status')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleDates',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='sche_dates_id')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('date', models.DateField(verbose_name='date')),
                ('day_of_week', models.CharField(max_length=10, null=True, verbose_name='day_of_week')),
                ('start_time', models.TimeField(verbose_name='actual_star_time')),
                ('end_time', models.TimeField(verbose_name='actual_end_time')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.doctor')),
            ],
        ),
    ]
