# Generated by Django 4.0.2 on 2022-03-09 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledates',
            name='clinic',
            field=models.ForeignKey(default=1130000, on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic'),
        ),
        migrations.AddField(
            model_name='scheduledates',
            name='doctor',
            field=models.ForeignKey(default=1170000, on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.doctor'),
        ),
    ]
