# Generated by Django 4.0.2 on 2022-03-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt', '0003_alter_clinic_options_remove_clinic_available_to_work_and_more'),
        ('schedules', '0002_scheduledates_clinic_scheduledates_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledates',
            name='e_time',
        ),
        migrations.RemoveField(
            model_name='scheduledates',
            name='s_time',
        ),
        migrations.AlterField(
            model_name='scheduledates',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.clinic'),
        ),
        migrations.AlterField(
            model_name='scheduledates',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt.doctor'),
        ),
        migrations.AlterField(
            model_name='scheduledates',
            name='end_time',
            field=models.TimeField(verbose_name='actual_end_time'),
        ),
        migrations.AlterField(
            model_name='scheduledates',
            name='start_time',
            field=models.TimeField(verbose_name='actual_star_time'),
        ),
    ]
