# Generated by Django 4.0.2 on 2022-03-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_alter_scheduledates_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
