# Generated by Django 4.0.2 on 2022-03-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='avail_times',
            field=models.CharField(max_length=10, verbose_name='time'),
        ),
    ]
