# Generated by Django 4.0.2 on 2022-04-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_alter_scheduledates_id_alter_timeslots_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledates',
            name='slug',
            field=models.SlugField(default='p', help_text='Unique Value for product page URL, created from name.', max_length=255),
            preserve_default=False,
        ),
    ]
